### ISSUE TITLE
environments do not load under latest release 

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-environments#16]
I have attached a script that will fail on Ubuntu 18.04, with a clean installation of the hpp-rbprm pipeline (although rbprm is not involved, I only include hpp default libraries in the attached script).

The command 

`loadObstacleModel ("hpp_environments", "multicontact/plateforme_not_flat", "planning")`

will output a parsing error, while 

`loadObstacleModel ("package://hpp_environments/urdf/multicontact/plateforme_not_flat.urdf", "planning")`

will work just fine. The error also occured with other packages and was reproduced by @pFernbach  on his computer.
To run the failing script just run:

`./run_manip.sh test.py`

Thanks !

[error.zip](https://github.com/humanoid-path-planner/hpp-environments/files/5306151/error.zip)

**Comment by jmirabel** [comment]
This is expected. With https://github.com/humanoid-path-planner/hpp-gepetto-viewer/pull/45, the error should be clearer.

**Comment by stonneau** [comment]
I see, thank you !
